spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.50.175.251:3306/GwentMirror
    username: root
    password: LiuLong123123+
    hikari:
      max-lifetime: 180000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ll.gwentmirror.entity
server:
  port: 8081


#ftp:
#  hostname: 110.42.155.172
#  port: 21
#  username: onemorechance_xyz
#  password: 123123cf
#  save-path:

file:
  uploadUrl: "/upload/"